% Clear existing MEX file.
clear Component_SFunction.mexw64;
if isfile('Component_SFunction.mexw64')
	delete Component_SFunction.mexw64;
end

% Compile MEX file.
mex -v -largeArrayDims ...
	-output Component_SFunction ...
	-Iplatform ...
	-Iinclude ...
	-Isrc ...
	-Llib -lESDL_Linear_Interpolation_amd64.lib ...
	-DCOMPILE_UNUSED_CODE ...
	-DESDL_PLATFORM_INTERNAL_BUILD ...
	-D_CRT_SECURE_NO_WARNINGS ...
	-DPC ...
	-DOBJECT ...
	platform\esdl_simulink_adapter.c ...
	platform\asimulinkManager.c ...
	platform\asimulinkHelper.c ...
	platform\asimulinkReference.c ...
	platform\asimulinkSchedule.c ...
	src\components_Component_Automatic.c ...
	src\components_FilterBy_Automatic.c ...
	src\components_Filter_Automatic.c ...
	src\components_InpOut_Automatic.c ...
	src\components_PID_Automatic.c ...
	src\components_RunningAverage_Automatic.c ...
	src\Component_SFunction_Automatic.c ...
	src\PID_PID_Automatic.c ...
	src\SystemLib_Delay_DelayValue_Impl.c ...
	;

% Create debug bus.
if isfile('busCreatorComponent_SFunction.m')
	run busCreatorComponent_SFunction;
end

% Create parameters.
if isfile('calibrationComponent_SFunction.m')
	run calibrationComponent_SFunction;
end
