/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.5.0
 * CODE GENERATOR:..............V7.5.0
 * COMPONENT:...................components.FilterBy
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_COMPONENTS_FILTERBY_AUTOMATIC_H_
#define _ASD_COMPONENTS_FILTERBY_AUTOMATIC_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "SystemLib_Delay_DelayValue_Impl.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'components_FilterBy_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * ---------------------------------------------------------------------------*/
struct components_FilterBy_Automatic_CAL_MEM_SUBSTRUCT {
   float32 K1;
   float32 K2;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'components_FilterBy_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'components_FilterBy_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct components_FilterBy_Automatic_RAM_SUBSTRUCT {
   struct SystemLib_Delay_DelayValue_Impl_RAM_SUBSTRUCT DelayValue_instance;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'components_FilterBy_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR CLASS 'components_FilterBy_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct components_FilterBy_Automatic {
   struct components_FilterBy_Automatic_CAL_MEM_SUBSTRUCT * components_FilterBy_Automatic_CAL_MEM;
   struct SystemLib_Delay_DelayValue_Impl DelayValue_instance;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR CLASS 'components_FilterBy_Automatic'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ..............components_FilterBy_Automatic */
#define _components_FilterBy_Automatic_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by class components_FilterBy_Automatic
 ******************************************************************************/
extern float32 components_FilterBy_Automatic_Filter (
               const struct components_FilterBy_Automatic * self,
   /* IN    */ const float32                                Inp,
   /* IN    */ const float32                                Ts
   );



#endif /* _ASD_COMPONENTS_FILTERBY_AUTOMATIC_H_ */
