/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.5.0
 * CODE GENERATOR:..............V7.5.0
 * COMPONENT:...................components.RunningAverage
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_RunningAverage_Automatic.h"
/******************************************************************************
 * BEGIN: source code of a multiple instance class
 ******************************************************************************/



#define c1_VAL (self->components_RunningAverage_Automatic_CAL_MEM->c1)
#define DelayValue_instance_2_REF (&(self->DelayValue_instance_2))
#define DelayValue_instance_3_REF (&(self->DelayValue_instance_3))
#define DelayValue_instance_4_REF (&(self->DelayValue_instance_4))
#define DelayValue_instance_5_REF (&(self->DelayValue_instance_5))
#define DelayValue_instance_6_REF (&(self->DelayValue_instance_6))
#define DelayValue_instance_7_REF (&(self->DelayValue_instance_7))
#define DelayValue_instance_8_REF (&(self->DelayValue_instance_8))
#define DelayValue_instance_9_REF (&(self->DelayValue_instance_9))
#define DelayValue_instance_REF (&(self->DelayValue_instance))


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_RunningAverage_Automatic_mean'
 * ----------------------------------------------------------------------------
 * model name:...................................'mean'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 components_RunningAverage_Automatic_mean (
               const struct components_RunningAverage_Automatic * self,
   /* IN    */ const float32                                      Inp
   )
{
   /* temp. variables */
   float32 _t1real32;

   SystemLib_Delay_DelayValue_Impl_compute(DelayValue_instance_REF, (float64)Inp);
   SystemLib_Delay_DelayValue_Impl_compute(DelayValue_instance_9_REF, SystemLib_Delay_DelayValue_Impl_value(DelayValue_instance_8_REF));
   SystemLib_Delay_DelayValue_Impl_compute(DelayValue_instance_8_REF, SystemLib_Delay_DelayValue_Impl_value(DelayValue_instance_7_REF));
   SystemLib_Delay_DelayValue_Impl_compute(DelayValue_instance_7_REF, SystemLib_Delay_DelayValue_Impl_value(DelayValue_instance_6_REF));
   SystemLib_Delay_DelayValue_Impl_compute(DelayValue_instance_6_REF, SystemLib_Delay_DelayValue_Impl_value(DelayValue_instance_5_REF));
   SystemLib_Delay_DelayValue_Impl_compute(DelayValue_instance_4_REF, SystemLib_Delay_DelayValue_Impl_value(DelayValue_instance_3_REF));
   SystemLib_Delay_DelayValue_Impl_compute(DelayValue_instance_3_REF, SystemLib_Delay_DelayValue_Impl_value(DelayValue_instance_2_REF));
   SystemLib_Delay_DelayValue_Impl_compute(DelayValue_instance_2_REF, SystemLib_Delay_DelayValue_Impl_value(DelayValue_instance_REF));
   SystemLib_Delay_DelayValue_Impl_compute(DelayValue_instance_5_REF, SystemLib_Delay_DelayValue_Impl_value(DelayValue_instance_4_REF));
   _t1real32
      = (float32)SystemLib_Delay_DelayValue_Impl_value(DelayValue_instance_9_REF) + (float32)SystemLib_Delay_DelayValue_Impl_value(DelayValue_instance_8_REF) + (float32)SystemLib_Delay_DelayValue_Impl_value(DelayValue_instance_7_REF) + (float32)SystemLib_Delay_DelayValue_Impl_value(DelayValue_instance_6_REF) + (float32)SystemLib_Delay_DelayValue_Impl_value(DelayValue_instance_5_REF) + (float32)SystemLib_Delay_DelayValue_Impl_value(DelayValue_instance_4_REF) + (float32)SystemLib_Delay_DelayValue_Impl_value(DelayValue_instance_3_REF) + (float32)SystemLib_Delay_DelayValue_Impl_value(DelayValue_instance_2_REF) + (float32)SystemLib_Delay_DelayValue_Impl_value(DelayValue_instance_REF) + Inp;
   return ((c1_VAL == 0.0F) ? _t1real32 : (_t1real32 / c1_VAL));
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_RunningAverage_Automatic_mean'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



