/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.5.0
 * CODE GENERATOR:..............V7.5.0
 * COMPONENT:...................components.Component
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_COMPONENTS_COMPONENT_AUTOMATIC_H_
#define _ASD_COMPONENTS_COMPONENT_AUTOMATIC_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "components_FilterBy_Automatic.h"
#include "components_RunningAverage_Automatic.h"
#include "PID_PID_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'components_Component_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * ---------------------------------------------------------------------------*/
struct components_Component_Automatic_CAL_MEM_SUBSTRUCT {
   struct components_FilterBy_Automatic_CAL_MEM_SUBSTRUCT FilterBy_instance;
   struct PID_PID_Automatic_CAL_MEM_SUBSTRUCT PID_instance;
   struct PID_PID_Automatic_CAL_MEM_SUBSTRUCT PID_instance_2;
   struct components_RunningAverage_Automatic_CAL_MEM_SUBSTRUCT RunningAverage_instance;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'components_Component_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'components_Component_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct components_Component_Automatic_RAM_SUBSTRUCT {
   float32 afterFilt;
   float32 afterInp;
   float32 afterRunAv;
   struct components_FilterBy_Automatic_RAM_SUBSTRUCT FilterBy_instance;
   struct PID_PID_Automatic_RAM_SUBSTRUCT PID_instance;
   struct PID_PID_Automatic_RAM_SUBSTRUCT PID_instance_2;
   struct components_RunningAverage_Automatic_RAM_SUBSTRUCT RunningAverage_instance;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'components_Component_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR MODULE 'components_Component_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct components_Component_Automatic {
   struct components_FilterBy_Automatic FilterBy_instance;
   struct PID_PID_Automatic PID_instance;
   struct PID_PID_Automatic PID_instance_2;
   struct components_RunningAverage_Automatic RunningAverage_instance;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR MODULE 'components_Component_Automatic'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: .............components_Component_Automatic */
#define _components_Component_Automatic_TYPE_DEF_




/* forward declaration of substruct variable 'components_Component_CAL_MEM' */
/* containing 'CAL_MEM' memory class tree */
extern struct components_Component_Automatic_CAL_MEM_SUBSTRUCT components_Component_CAL_MEM;

/* forward declaration of substruct variable 'components_Component_RAM' */
/* containing 'RAM' memory class tree */
extern struct components_Component_Automatic_RAM_SUBSTRUCT components_Component_RAM;

/* forward declaration of component variable 'components_Component' */
/* containing 'ROM' memory class tree */
extern const struct components_Component_Automatic components_Component;

/******************************************************************************
 * BEGIN: declaration of global C functions defined by module components_Component_Automatic
 ******************************************************************************/
extern void components_Component_Automatic_Spid (void);



#endif /* _ASD_COMPONENTS_COMPONENT_AUTOMATIC_H_ */
