/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.5.0
 * CODE GENERATOR:..............V7.5.0
 * COMPONENT:...................components.PID
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_COMPONENTS_PID_AUTOMATIC_H_
#define _ASD_COMPONENTS_PID_AUTOMATIC_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"


/* component structure for module COMPONENTS_PID_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ...................components_PID_Automatic */
#define _components_PID_Automatic_TYPE_DEF_



/******************************************************************************
 * BEGIN: declaration of global C variables exported by module components_PID_Automatic
 ******************************************************************************/


/* declaration of messages */
extern float32 components_PID_PressSet;
extern float32 components_PID_TsPID;
extern float32 components_PID_qD;
extern float32 components_PID_qI;
extern float32 components_PID_qP;


#endif /* _ASD_COMPONENTS_PID_AUTOMATIC_H_ */
