/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.5.0
 * CODE GENERATOR:..............V7.5.0
 * COMPONENT:...................components.InpOut
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_COMPONENTS_INPOUT_AUTOMATIC_H_
#define _ASD_COMPONENTS_INPOUT_AUTOMATIC_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"


/* component structure for module COMPONENTS_INPOUT_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ................components_InpOut_Automatic */
#define _components_InpOut_Automatic_TYPE_DEF_



/******************************************************************************
 * BEGIN: declaration of global C variables exported by module components_InpOut_Automatic
 ******************************************************************************/


/* declaration of messages */
extern float32 components_InpOut_D_Out;
extern float32 components_InpOut_I_Out;
extern float32 components_InpOut_Input;
extern float32 components_InpOut_P_Out;


#endif /* _ASD_COMPONENTS_INPOUT_AUTOMATIC_H_ */
