/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.5.0
 * CODE GENERATOR:..............V7.5.0
 * COMPONENT:...................components.RunningAverage
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_COMPONENTS_RUNNINGAVERAGE_AUTOMATIC_H_
#define _ASD_COMPONENTS_RUNNINGAVERAGE_AUTOMATIC_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "SystemLib_Delay_DelayValue_Impl.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'components_RunningAverage_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * ---------------------------------------------------------------------------*/
struct components_RunningAverage_Automatic_CAL_MEM_SUBSTRUCT {
   float32 c1;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'components_RunningAverage_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'components_RunningAverage_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct components_RunningAverage_Automatic_RAM_SUBSTRUCT {
   struct SystemLib_Delay_DelayValue_Impl_RAM_SUBSTRUCT DelayValue_instance;
   struct SystemLib_Delay_DelayValue_Impl_RAM_SUBSTRUCT DelayValue_instance_2;
   struct SystemLib_Delay_DelayValue_Impl_RAM_SUBSTRUCT DelayValue_instance_3;
   struct SystemLib_Delay_DelayValue_Impl_RAM_SUBSTRUCT DelayValue_instance_4;
   struct SystemLib_Delay_DelayValue_Impl_RAM_SUBSTRUCT DelayValue_instance_5;
   struct SystemLib_Delay_DelayValue_Impl_RAM_SUBSTRUCT DelayValue_instance_6;
   struct SystemLib_Delay_DelayValue_Impl_RAM_SUBSTRUCT DelayValue_instance_7;
   struct SystemLib_Delay_DelayValue_Impl_RAM_SUBSTRUCT DelayValue_instance_8;
   struct SystemLib_Delay_DelayValue_Impl_RAM_SUBSTRUCT DelayValue_instance_9;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'components_RunningAverage_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR CLASS 'components_RunningAverage_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct components_RunningAverage_Automatic {
   struct components_RunningAverage_Automatic_CAL_MEM_SUBSTRUCT * components_RunningAverage_Automatic_CAL_MEM;
   struct SystemLib_Delay_DelayValue_Impl DelayValue_instance;
   struct SystemLib_Delay_DelayValue_Impl DelayValue_instance_2;
   struct SystemLib_Delay_DelayValue_Impl DelayValue_instance_3;
   struct SystemLib_Delay_DelayValue_Impl DelayValue_instance_4;
   struct SystemLib_Delay_DelayValue_Impl DelayValue_instance_5;
   struct SystemLib_Delay_DelayValue_Impl DelayValue_instance_6;
   struct SystemLib_Delay_DelayValue_Impl DelayValue_instance_7;
   struct SystemLib_Delay_DelayValue_Impl DelayValue_instance_8;
   struct SystemLib_Delay_DelayValue_Impl DelayValue_instance_9;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR CLASS 'components_RunningAverage_Automatic'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ........components_RunningAverage_Automatic */
#define _components_RunningAverage_Automatic_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by class components_RunningAverage_Automatic
 ******************************************************************************/
extern float32 components_RunningAverage_Automatic_mean (
               const struct components_RunningAverage_Automatic * self,
   /* IN    */ const float32                                      Inp
   );



#endif /* _ASD_COMPONENTS_RUNNINGAVERAGE_AUTOMATIC_H_ */
