/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.5.0
 * CODE GENERATOR:..............V7.5.0
 * COMPONENT:...................components.Component
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/


/*-----------------------------------------------------------------------------
 *    Defines
 *----------------------------------------------------------------------------*/

#define __ASD_REQUIRES_OS_INFACE

/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_Component_Automatic.h"
#include "components_Filter_Automatic.h"
#include "components_InpOut_Automatic.h"
#include "components_PID_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'components_Component_CAL_MEM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * model name:...................................'components_Component'
 * data set:.....................................'COMPONENTS_COMPONENT_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct components_Component_Automatic_CAL_MEM_SUBSTRUCT components_Component_CAL_MEM = {
   /* substruct: components_Component_CAL_MEM.FilterBy_instance (modeled as:'FilterBy_instance.components_Component') */
   {
      /* struct element:'components_Component_CAL_MEM.FilterBy_instance.K2' (modeled as:'K2.FilterBy_instance.components_Component') */
      1.0F
   },
   /* substruct: components_Component_CAL_MEM.PID_instance (modeled as:'PID_instance.components_Component') */
   {
      /* struct element:'components_Component_CAL_MEM.PID_instance.cD_Max' (modeled as:'cD_Max.PID_instance.components_Component') */
      100.0F,
      /* struct element:'components_Component_CAL_MEM.PID_instance.cD_Min' (modeled as:'cD_Min.PID_instance.components_Component') */
      -100.0F,
      /* struct element:'components_Component_CAL_MEM.PID_instance.cI_Max' (modeled as:'cI_Max.PID_instance.components_Component') */
      100.0F,
      /* struct element:'components_Component_CAL_MEM.PID_instance.cI_Min' (modeled as:'cI_Min.PID_instance.components_Component') */
      -100.0F,
      /* struct element:'components_Component_CAL_MEM.PID_instance.cP_Max' (modeled as:'cP_Max.PID_instance.components_Component') */
      100.0F,
      /* struct element:'components_Component_CAL_MEM.PID_instance.cP_Min' (modeled as:'cP_Min.PID_instance.components_Component') */
      -100.0F
   },
   /* substruct: components_Component_CAL_MEM.PID_instance_3 (modeled as:'PID_instance_3.components_Component') */
   {
      /* struct element:'components_Component_CAL_MEM.PID_instance_3.cD_Max' (modeled as:'cD_Max.PID_instance_3.components_Component') */
      100.0F,
      /* struct element:'components_Component_CAL_MEM.PID_instance_3.cD_Min' (modeled as:'cD_Min.PID_instance_3.components_Component') */
      -100.0F,
      /* struct element:'components_Component_CAL_MEM.PID_instance_3.cI_Max' (modeled as:'cI_Max.PID_instance_3.components_Component') */
      100.0F,
      /* struct element:'components_Component_CAL_MEM.PID_instance_3.cI_Min' (modeled as:'cI_Min.PID_instance_3.components_Component') */
      -100.0F,
      /* struct element:'components_Component_CAL_MEM.PID_instance_3.cP_Max' (modeled as:'cP_Max.PID_instance_3.components_Component') */
      100.0F,
      /* struct element:'components_Component_CAL_MEM.PID_instance_3.cP_Min' (modeled as:'cP_Min.PID_instance_3.components_Component') */
      -100.0F
   },
   /* substruct: components_Component_CAL_MEM.RunningAverage_instance (modeled as:'RunningAverage_instance.components_Component') */
   {
      /* struct element:'components_Component_CAL_MEM.RunningAverage_instance.c1' (modeled as:'c1.RunningAverage_instance.components_Component') */
      10.0F
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'components_Component_CAL_MEM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'components_Component_RAM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * model name:...................................'components_Component'
 * data set:.....................................'COMPONENTS_COMPONENT_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct components_Component_Automatic_RAM_SUBSTRUCT components_Component_RAM = {
   /* struct element:'components_Component_RAM.afterFilt' (modeled as:'afterFilt.components_Component') */
   0.0F,
   /* struct element:'components_Component_RAM.afterInp' (modeled as:'afterInp.components_Component') */
   0.0F,
   /* struct element:'components_Component_RAM.afterRunAv' (modeled as:'afterRunAv.components_Component') */
   0.0F,
   /* substruct: components_Component_RAM.FilterBy_instance (modeled as:'FilterBy_instance.components_Component') */
   {
      /* substruct: components_Component_RAM.FilterBy_instance.DelayValue_instance (modeled as:'DelayValue_instance.FilterBy_instance.components_Component') */
      {
         /* struct element:'components_Component_RAM.FilterBy_instance.DelayValue_instance.memory1' (modeled as:'memory1.DelayValue_instance.FilterBy_instance.components_Component') */
         0.0,
         /* struct element:'components_Component_RAM.FilterBy_instance.DelayValue_instance.memory2' (modeled as:'memory2.DelayValue_instance.FilterBy_instance.components_Component') */
         0.0
      }
   },
   /* substruct: components_Component_RAM.PID_instance (modeled as:'PID_instance.components_Component') */
   {
      /* struct element:'components_Component_RAM.PID_instance.Error' (modeled as:'Error.PID_instance.components_Component') */
      0.0F,
      /* struct element:'components_Component_RAM.PID_instance.InpOsc' (modeled as:'InpOsc.PID_instance.components_Component') */
      0.0F,
      /* struct element:'components_Component_RAM.PID_instance.afterD' (modeled as:'afterD.PID_instance.components_Component') */
      0.0F,
      /* struct element:'components_Component_RAM.PID_instance.afterI' (modeled as:'afterI.PID_instance.components_Component') */
      0.0F,
      /* struct element:'components_Component_RAM.PID_instance.afterP' (modeled as:'afterP.PID_instance.components_Component') */
      0.0F,
      /* struct element:'components_Component_RAM.PID_instance.pMemory' (modeled as:'pMemory.PID_instance.components_Component') */
      0.0F,
      /* substruct: components_Component_RAM.PID_instance.DelayValue_instance_5 (modeled as:'DelayValue_instance_5.PID_instance.components_Component') */
      {
         /* struct element:'components_Component_RAM.PID_instance.DelayValue_instance_5.memory1' (modeled as:'memory1.DelayValue_instance_5.PID_instance.components_Component') */
         0.0,
         /* struct element:'components_Component_RAM.PID_instance.DelayValue_instance_5.memory2' (modeled as:'memory2.DelayValue_instance_5.PID_instance.components_Component') */
         0.0
      }
   },
   /* substruct: components_Component_RAM.PID_instance_3 (modeled as:'PID_instance_3.components_Component') */
   {
      /* struct element:'components_Component_RAM.PID_instance_3.Error' (modeled as:'Error.PID_instance_3.components_Component') */
      0.0F,
      /* struct element:'components_Component_RAM.PID_instance_3.InpOsc' (modeled as:'InpOsc.PID_instance_3.components_Component') */
      0.0F,
      /* struct element:'components_Component_RAM.PID_instance_3.afterD' (modeled as:'afterD.PID_instance_3.components_Component') */
      0.0F,
      /* struct element:'components_Component_RAM.PID_instance_3.afterI' (modeled as:'afterI.PID_instance_3.components_Component') */
      0.0F,
      /* struct element:'components_Component_RAM.PID_instance_3.afterP' (modeled as:'afterP.PID_instance_3.components_Component') */
      0.0F,
      /* struct element:'components_Component_RAM.PID_instance_3.pMemory' (modeled as:'pMemory.PID_instance_3.components_Component') */
      0.0F,
      /* substruct: components_Component_RAM.PID_instance_3.DelayValue_instance_5 (modeled as:'DelayValue_instance_5.PID_instance_3.components_Component') */
      {
         /* struct element:'components_Component_RAM.PID_instance_3.DelayValue_instance_5.memory1' (modeled as:'memory1.DelayValue_instance_5.PID_instance_3.components_Component') */
         0.0,
         /* struct element:'components_Component_RAM.PID_instance_3.DelayValue_instance_5.memory2' (modeled as:'memory2.DelayValue_instance_5.PID_instance_3.components_Component') */
         0.0
      }
   },
   /* substruct: components_Component_RAM.RunningAverage_instance (modeled as:'RunningAverage_instance.components_Component') */
   {
      /* substruct: components_Component_RAM.RunningAverage_instance.DelayValue_instance (modeled as:'DelayValue_instance.RunningAverage_instance.components_Component') */
      {
         /* struct element:'components_Component_RAM.RunningAverage_instance.DelayValue_instance.memory1' (modeled as:'memory1.DelayValue_instance.RunningAverage_instance.components_Component') */
         0.0,
         /* struct element:'components_Component_RAM.RunningAverage_instance.DelayValue_instance.memory2' (modeled as:'memory2.DelayValue_instance.RunningAverage_instance.components_Component') */
         0.0
      },
      /* substruct: components_Component_RAM.RunningAverage_instance.DelayValue_instance_2 (modeled as:'DelayValue_instance_2.RunningAverage_instance.components_Component') */
      {
         /* struct element:'components_Component_RAM.RunningAverage_instance.DelayValue_instance_2.memory1' (modeled as:'memory1.DelayValue_instance_2.RunningAverage_instance.components_Component') */
         0.0,
         /* struct element:'components_Component_RAM.RunningAverage_instance.DelayValue_instance_2.memory2' (modeled as:'memory2.DelayValue_instance_2.RunningAverage_instance.components_Component') */
         0.0
      },
      /* substruct: components_Component_RAM.RunningAverage_instance.DelayValue_instance_3 (modeled as:'DelayValue_instance_3.RunningAverage_instance.components_Component') */
      {
         /* struct element:'components_Component_RAM.RunningAverage_instance.DelayValue_instance_3.memory1' (modeled as:'memory1.DelayValue_instance_3.RunningAverage_instance.components_Component') */
         0.0,
         /* struct element:'components_Component_RAM.RunningAverage_instance.DelayValue_instance_3.memory2' (modeled as:'memory2.DelayValue_instance_3.RunningAverage_instance.components_Component') */
         0.0
      },
      /* substruct: components_Component_RAM.RunningAverage_instance.DelayValue_instance_4 (modeled as:'DelayValue_instance_4.RunningAverage_instance.components_Component') */
      {
         /* struct element:'components_Component_RAM.RunningAverage_instance.DelayValue_instance_4.memory1' (modeled as:'memory1.DelayValue_instance_4.RunningAverage_instance.components_Component') */
         0.0,
         /* struct element:'components_Component_RAM.RunningAverage_instance.DelayValue_instance_4.memory2' (modeled as:'memory2.DelayValue_instance_4.RunningAverage_instance.components_Component') */
         0.0
      },
      /* substruct: components_Component_RAM.RunningAverage_instance.DelayValue_instance_5 (modeled as:'DelayValue_instance_5.RunningAverage_instance.components_Component') */
      {
         /* struct element:'components_Component_RAM.RunningAverage_instance.DelayValue_instance_5.memory1' (modeled as:'memory1.DelayValue_instance_5.RunningAverage_instance.components_Component') */
         0.0,
         /* struct element:'components_Component_RAM.RunningAverage_instance.DelayValue_instance_5.memory2' (modeled as:'memory2.DelayValue_instance_5.RunningAverage_instance.components_Component') */
         0.0
      },
      /* substruct: components_Component_RAM.RunningAverage_instance.DelayValue_instance_6 (modeled as:'DelayValue_instance_6.RunningAverage_instance.components_Component') */
      {
         /* struct element:'components_Component_RAM.RunningAverage_instance.DelayValue_instance_6.memory1' (modeled as:'memory1.DelayValue_instance_6.RunningAverage_instance.components_Component') */
         0.0,
         /* struct element:'components_Component_RAM.RunningAverage_instance.DelayValue_instance_6.memory2' (modeled as:'memory2.DelayValue_instance_6.RunningAverage_instance.components_Component') */
         0.0
      },
      /* substruct: components_Component_RAM.RunningAverage_instance.DelayValue_instance_7 (modeled as:'DelayValue_instance_7.RunningAverage_instance.components_Component') */
      {
         /* struct element:'components_Component_RAM.RunningAverage_instance.DelayValue_instance_7.memory1' (modeled as:'memory1.DelayValue_instance_7.RunningAverage_instance.components_Component') */
         0.0,
         /* struct element:'components_Component_RAM.RunningAverage_instance.DelayValue_instance_7.memory2' (modeled as:'memory2.DelayValue_instance_7.RunningAverage_instance.components_Component') */
         0.0
      },
      /* substruct: components_Component_RAM.RunningAverage_instance.DelayValue_instance_8 (modeled as:'DelayValue_instance_8.RunningAverage_instance.components_Component') */
      {
         /* struct element:'components_Component_RAM.RunningAverage_instance.DelayValue_instance_8.memory1' (modeled as:'memory1.DelayValue_instance_8.RunningAverage_instance.components_Component') */
         0.0,
         /* struct element:'components_Component_RAM.RunningAverage_instance.DelayValue_instance_8.memory2' (modeled as:'memory2.DelayValue_instance_8.RunningAverage_instance.components_Component') */
         0.0
      },
      /* substruct: components_Component_RAM.RunningAverage_instance.DelayValue_instance_9 (modeled as:'DelayValue_instance_9.RunningAverage_instance.components_Component') */
      {
         /* struct element:'components_Component_RAM.RunningAverage_instance.DelayValue_instance_9.memory1' (modeled as:'memory1.DelayValue_instance_9.RunningAverage_instance.components_Component') */
         0.0,
         /* struct element:'components_Component_RAM.RunningAverage_instance.DelayValue_instance_9.memory2' (modeled as:'memory2.DelayValue_instance_9.RunningAverage_instance.components_Component') */
         0.0
      }
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'components_Component_RAM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF COMPONENT VARIABLE 'components_Component'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'components_Component'
 * data set:.....................................'COMPONENTS_COMPONENT_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
const struct components_Component_Automatic components_Component = {
   /* substruct: components_Component.FilterBy_instance (modeled as:'FilterBy_instance.components_Component') */
   {
      /* type descriptor pointer 'components_FilterBy_Automatic_CAL_MEM' for memory class substruct for 'CAL_MEM' */
      &components_Component_CAL_MEM.FilterBy_instance,
      /* substruct: components_Component.FilterBy_instance.DelayValue_instance (modeled as:'DelayValue_instance.FilterBy_instance.components_Component') */
      {
         /* type descriptor pointer 'SystemLib_Delay_DelayValue_Impl_RAM' for memory class substruct for 'RAM' */
         &components_Component_RAM.FilterBy_instance.DelayValue_instance
      }
   },
   /* substruct: components_Component.PID_instance (modeled as:'PID_instance.components_Component') */
   {
      /* type descriptor pointer 'PID_PID_Automatic_CAL_MEM' for memory class substruct for 'CAL_MEM' */
      &components_Component_CAL_MEM.PID_instance,
      /* type descriptor pointer 'PID_PID_Automatic_RAM' for memory class substruct for 'RAM' */
      &components_Component_RAM.PID_instance,
      /* substruct: components_Component.PID_instance.DelayValue_instance_5 (modeled as:'DelayValue_instance_5.PID_instance.components_Component') */
      {
         /* type descriptor pointer 'SystemLib_Delay_DelayValue_Impl_RAM' for memory class substruct for 'RAM' */
         &components_Component_RAM.PID_instance.DelayValue_instance_5
      }
   },
   /* substruct: components_Component.PID_instance_3 (modeled as:'PID_instance_3.components_Component') */
   {
      /* type descriptor pointer 'PID_PID_Automatic_CAL_MEM' for memory class substruct for 'CAL_MEM' */
      &components_Component_CAL_MEM.PID_instance_3,
      /* type descriptor pointer 'PID_PID_Automatic_RAM' for memory class substruct for 'RAM' */
      &components_Component_RAM.PID_instance_3,
      /* substruct: components_Component.PID_instance_3.DelayValue_instance_5 (modeled as:'DelayValue_instance_5.PID_instance_3.components_Component') */
      {
         /* type descriptor pointer 'SystemLib_Delay_DelayValue_Impl_RAM' for memory class substruct for 'RAM' */
         &components_Component_RAM.PID_instance_3.DelayValue_instance_5
      }
   },
   /* substruct: components_Component.RunningAverage_instance (modeled as:'RunningAverage_instance.components_Component') */
   {
      /* type descriptor pointer 'components_RunningAverage_Automatic_CAL_MEM' for memory class substruct for 'CAL_MEM' */
      &components_Component_CAL_MEM.RunningAverage_instance,
      /* substruct: components_Component.RunningAverage_instance.DelayValue_instance (modeled as:'DelayValue_instance.RunningAverage_instance.components_Component') */
      {
         /* type descriptor pointer 'SystemLib_Delay_DelayValue_Impl_RAM' for memory class substruct for 'RAM' */
         &components_Component_RAM.RunningAverage_instance.DelayValue_instance
      },
      /* substruct: components_Component.RunningAverage_instance.DelayValue_instance_2 (modeled as:'DelayValue_instance_2.RunningAverage_instance.components_Component') */
      {
         /* type descriptor pointer 'SystemLib_Delay_DelayValue_Impl_RAM' for memory class substruct for 'RAM' */
         &components_Component_RAM.RunningAverage_instance.DelayValue_instance_2
      },
      /* substruct: components_Component.RunningAverage_instance.DelayValue_instance_3 (modeled as:'DelayValue_instance_3.RunningAverage_instance.components_Component') */
      {
         /* type descriptor pointer 'SystemLib_Delay_DelayValue_Impl_RAM' for memory class substruct for 'RAM' */
         &components_Component_RAM.RunningAverage_instance.DelayValue_instance_3
      },
      /* substruct: components_Component.RunningAverage_instance.DelayValue_instance_4 (modeled as:'DelayValue_instance_4.RunningAverage_instance.components_Component') */
      {
         /* type descriptor pointer 'SystemLib_Delay_DelayValue_Impl_RAM' for memory class substruct for 'RAM' */
         &components_Component_RAM.RunningAverage_instance.DelayValue_instance_4
      },
      /* substruct: components_Component.RunningAverage_instance.DelayValue_instance_5 (modeled as:'DelayValue_instance_5.RunningAverage_instance.components_Component') */
      {
         /* type descriptor pointer 'SystemLib_Delay_DelayValue_Impl_RAM' for memory class substruct for 'RAM' */
         &components_Component_RAM.RunningAverage_instance.DelayValue_instance_5
      },
      /* substruct: components_Component.RunningAverage_instance.DelayValue_instance_6 (modeled as:'DelayValue_instance_6.RunningAverage_instance.components_Component') */
      {
         /* type descriptor pointer 'SystemLib_Delay_DelayValue_Impl_RAM' for memory class substruct for 'RAM' */
         &components_Component_RAM.RunningAverage_instance.DelayValue_instance_6
      },
      /* substruct: components_Component.RunningAverage_instance.DelayValue_instance_7 (modeled as:'DelayValue_instance_7.RunningAverage_instance.components_Component') */
      {
         /* type descriptor pointer 'SystemLib_Delay_DelayValue_Impl_RAM' for memory class substruct for 'RAM' */
         &components_Component_RAM.RunningAverage_instance.DelayValue_instance_7
      },
      /* substruct: components_Component.RunningAverage_instance.DelayValue_instance_8 (modeled as:'DelayValue_instance_8.RunningAverage_instance.components_Component') */
      {
         /* type descriptor pointer 'SystemLib_Delay_DelayValue_Impl_RAM' for memory class substruct for 'RAM' */
         &components_Component_RAM.RunningAverage_instance.DelayValue_instance_8
      },
      /* substruct: components_Component.RunningAverage_instance.DelayValue_instance_9 (modeled as:'DelayValue_instance_9.RunningAverage_instance.components_Component') */
      {
         /* type descriptor pointer 'SystemLib_Delay_DelayValue_Impl_RAM' for memory class substruct for 'RAM' */
         &components_Component_RAM.RunningAverage_instance.DelayValue_instance_9
      }
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF COMPONENT VARIABLE 'components_Component'
 ******************************************************************************/





#define afterFilt_VAL (components_Component_RAM.afterFilt)
#define afterInp_VAL (components_Component_RAM.afterInp)
#define afterRunAv_VAL (components_Component_RAM.afterRunAv)
#define FilterBy_instance_REF (&(components_Component.FilterBy_instance))
#define PID_instance_3_REF (&(components_Component.PID_instance_3))
#define RunningAverage_instance_REF (&(components_Component.RunningAverage_instance))


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF PROCESS 'components_Component_Automatic_Spid'
 * ----------------------------------------------------------------------------
 * model name:...................................'Spid'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/
/* messages used by this process */
#define components_Filter_K1__components_Component_Automatic_Spid (components_Filter_K1)
#define components_Filter_TsFilter__components_Component_Automatic_Spid (components_Filter_TsFilter)
#define components_InpOut_D_Out__components_Component_Automatic_Spid (components_InpOut_D_Out)
#define components_InpOut_I_Out__components_Component_Automatic_Spid (components_InpOut_I_Out)
#define components_InpOut_Input__components_Component_Automatic_Spid (components_InpOut_Input)
#define components_InpOut_P_Out__components_Component_Automatic_Spid (components_InpOut_P_Out)
#define components_PID_PressSet__components_Component_Automatic_Spid (components_PID_PressSet)
#define components_PID_TsPID__components_Component_Automatic_Spid (components_PID_TsPID)
#define components_PID_qD__components_Component_Automatic_Spid (components_PID_qD)
#define components_PID_qI__components_Component_Automatic_Spid (components_PID_qI)
#define components_PID_qP__components_Component_Automatic_Spid (components_PID_qP)


void components_Component_Automatic_Spid (void)
{
   afterInp_VAL = components_InpOut_Input__components_Component_Automatic_Spid;
   afterRunAv_VAL
      = components_RunningAverage_Automatic_mean(RunningAverage_instance_REF, afterInp_VAL);
   afterFilt_VAL
      = components_FilterBy_Automatic_Filter(FilterBy_instance_REF, components_PID_PressSet__components_Component_Automatic_Spid, components_Filter_TsFilter__components_Component_Automatic_Spid, components_Filter_K1__components_Component_Automatic_Spid);
   PID_PID_Automatic_Regulator(PID_instance_3_REF, afterFilt_VAL, afterRunAv_VAL, components_PID_qP__components_Component_Automatic_Spid, components_PID_qI__components_Component_Automatic_Spid, components_PID_qD__components_Component_Automatic_Spid, components_PID_TsPID__components_Component_Automatic_Spid);
   components_InpOut_P_Out__components_Component_Automatic_Spid = PID_PID_Automatic_P_OUT(PID_instance_3_REF);
   components_InpOut_I_Out__components_Component_Automatic_Spid = PID_PID_Automatic_I_OUT(PID_instance_3_REF);
   components_InpOut_D_Out__components_Component_Automatic_Spid = PID_PID_Automatic_D_OUT(PID_instance_3_REF);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF PROCESS 'components_Component_Automatic_Spid'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



