/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.5.0
 * CODE GENERATOR:..............V7.5.0
 * COMPONENT:...................components.Filter
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_COMPONENTS_FILTER_AUTOMATIC_H_
#define _ASD_COMPONENTS_FILTER_AUTOMATIC_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"


/* component structure for module COMPONENTS_FILTER_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ................components_Filter_Automatic */
#define _components_Filter_Automatic_TYPE_DEF_



/******************************************************************************
 * BEGIN: declaration of global C variables exported by module components_Filter_Automatic
 ******************************************************************************/


/* declaration of messages */
extern float32 components_Filter_K1;
extern float32 components_Filter_TsFilter;


#endif /* _ASD_COMPONENTS_FILTER_AUTOMATIC_H_ */
