/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.5.0
 * CODE GENERATOR:..............V7.5.0
 * COMPONENT:...................components.FilterBy
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_FilterBy_Automatic.h"
/******************************************************************************
 * BEGIN: source code of a multiple instance class
 ******************************************************************************/



#define DelayValue_instance_REF (&(self->DelayValue_instance))
#define K2_VAL (self->components_FilterBy_Automatic_CAL_MEM->K2)


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_FilterBy_Automatic_Filter'
 * ----------------------------------------------------------------------------
 * model name:...................................'Filter'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 components_FilterBy_Automatic_Filter (
               const struct components_FilterBy_Automatic * self,
   /* IN    */ const float32                                Inp,
   /* IN    */ const float32                                Ts,
   /* IN    */ const float32                                K1
   )
{
   SystemLib_Delay_DelayValue_Impl_compute(DelayValue_instance_REF, ((((K1 == 0.0) ? Ts : ((float64)Ts / K1))) * (((float64)Inp * K2_VAL) - SystemLib_Delay_DelayValue_Impl_value(DelayValue_instance_REF))) + SystemLib_Delay_DelayValue_Impl_value(DelayValue_instance_REF));
   return ((((K1 == 0.0F) ? Ts : (Ts / K1))) * ((Inp * K2_VAL) - (float32)SystemLib_Delay_DelayValue_Impl_value(DelayValue_instance_REF))) + (float32)SystemLib_Delay_DelayValue_Impl_value(DelayValue_instance_REF);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_FilterBy_Automatic_Filter'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



