/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.5.0
 * CODE GENERATOR:..............V7.5.0
 * COMPONENT:...................Component_SFunction
 * REPRESENTATION:..............
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_COMPONENT_SFUNCTION_AUTOMATIC_H_
#define _ASD_COMPONENT_SFUNCTION_AUTOMATIC_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "components_Component_Automatic.h"
#include "components_Filter_Automatic.h"
#include "components_InpOut_Automatic.h"
#include "components_PID_Automatic.h"


/* component structure for project COMPONENT_SFUNCTION_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ..............Component_SFunction_Automatic */
#define _Component_SFunction_Automatic_TYPE_DEF_



/******************************************************************************
 * BEGIN: declaration of global C variables exported by project Component_SFunction_Automatic
 ******************************************************************************/



#endif /* _ASD_COMPONENT_SFUNCTION_AUTOMATIC_H_ */
