/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.5.0
 * CODE GENERATOR:..............V7.5.0
 * COMPONENT:...................PID.PID
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "PID_PID_Automatic.h"
/******************************************************************************
 * BEGIN: source code of a multiple instance class
 ******************************************************************************/



#define afterD_VAL (self->PID_PID_Automatic_RAM->afterD)
#define afterI_VAL (self->PID_PID_Automatic_RAM->afterI)
#define afterP_VAL (self->PID_PID_Automatic_RAM->afterP)
#define cD_Max_VAL (self->PID_PID_Automatic_CAL_MEM->cD_Max)
#define cD_Min_VAL (self->PID_PID_Automatic_CAL_MEM->cD_Min)
#define cI_Max_VAL (self->PID_PID_Automatic_CAL_MEM->cI_Max)
#define cI_Min_VAL (self->PID_PID_Automatic_CAL_MEM->cI_Min)
#define cP_Max_VAL (self->PID_PID_Automatic_CAL_MEM->cP_Max)
#define cP_Min_VAL (self->PID_PID_Automatic_CAL_MEM->cP_Min)
#define DelayValue_instance_5_REF (&(self->DelayValue_instance_5))
#define Error_VAL (self->PID_PID_Automatic_RAM->Error)
#define InpOsc_VAL (self->PID_PID_Automatic_RAM->InpOsc)


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'PID_PID_Automatic_D_OUT'
 * ----------------------------------------------------------------------------
 * model name:...................................'D_OUT'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 PID_PID_Automatic_D_OUT ( const struct PID_PID_Automatic * self)
{
   return afterD_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'PID_PID_Automatic_D_OUT'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'PID_PID_Automatic_I_OUT'
 * ----------------------------------------------------------------------------
 * model name:...................................'I_OUT'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 PID_PID_Automatic_I_OUT ( const struct PID_PID_Automatic * self)
{
   return afterI_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'PID_PID_Automatic_I_OUT'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'PID_PID_Automatic_P_OUT'
 * ----------------------------------------------------------------------------
 * model name:...................................'P_OUT'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 PID_PID_Automatic_P_OUT ( const struct PID_PID_Automatic * self)
{
   return afterP_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'PID_PID_Automatic_P_OUT'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'PID_PID_Automatic_Regulator'
 * ----------------------------------------------------------------------------
 * model name:...................................'Regulator'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void PID_PID_Automatic_Regulator (
               const struct PID_PID_Automatic * self,
   /* IN    */ const float32                    PressureSet,
   /* IN    */ const float32                    InpPressure,
   /* IN    */ const float32                    qP,
   /* IN    */ const float32                    qI,
   /* IN    */ const float32                    qD,
   /* IN    */ const float32                    dT_
   )
{
   /* temp. variables */
   float32 _t1real32;

   _t1real32
      = (float32)SystemLib_Delay_DelayValue_Impl_value(DelayValue_instance_5_REF) - Error_VAL;
   _t1real32 = qD * (((dT_ == 0.0F) ? _t1real32 : (_t1real32 / dT_)));
   _t1real32 = ((cD_Min_VAL >= _t1real32) ? cD_Min_VAL : _t1real32);
   afterD_VAL = ((_t1real32 <= cD_Max_VAL) ? _t1real32 : cD_Max_VAL);
   _t1real32 = qP * Error_VAL;
   _t1real32 = ((cP_Min_VAL >= _t1real32) ? cP_Min_VAL : _t1real32);
   afterP_VAL = ((_t1real32 <= cP_Max_VAL) ? _t1real32 : cP_Max_VAL);
   InpOsc_VAL = PressureSet;
   Error_VAL = InpOsc_VAL - InpPressure;
   SystemLib_Delay_DelayValue_Impl_compute(DelayValue_instance_5_REF, (float64)Error_VAL);
   _t1real32 = (dT_ * qI * Error_VAL) + afterI_VAL;
   _t1real32 = ((cI_Min_VAL >= _t1real32) ? cI_Min_VAL : _t1real32);
   afterI_VAL = ((_t1real32 <= cI_Max_VAL) ? _t1real32 : cI_Max_VAL);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'PID_PID_Automatic_Regulator'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



