/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.5.0
 * CODE GENERATOR:..............V7.5.0
 * COMPONENT:...................PID.PID
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_PID_PID_AUTOMATIC_H_
#define _ASD_PID_PID_AUTOMATIC_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "SystemLib_Delay_DelayValue_Impl.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'PID_PID_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * ---------------------------------------------------------------------------*/
struct PID_PID_Automatic_CAL_MEM_SUBSTRUCT {
   float32 cD_Max;
   float32 cD_Min;
   float32 cI_Max;
   float32 cI_Min;
   float32 cP_Max;
   float32 cP_Min;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'PID_PID_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'PID_PID_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct PID_PID_Automatic_RAM_SUBSTRUCT {
   float32 Error;
   float32 InpOsc;
   float32 afterD;
   float32 afterI;
   float32 afterP;
   float32 pMemory;
   struct SystemLib_Delay_DelayValue_Impl_RAM_SUBSTRUCT DelayValue_instance_5;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'PID_PID_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR CLASS 'PID_PID_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct PID_PID_Automatic {
   struct PID_PID_Automatic_CAL_MEM_SUBSTRUCT * PID_PID_Automatic_CAL_MEM;
   struct PID_PID_Automatic_RAM_SUBSTRUCT * PID_PID_Automatic_RAM;
   struct SystemLib_Delay_DelayValue_Impl DelayValue_instance_5;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR CLASS 'PID_PID_Automatic'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ..........................PID_PID_Automatic */
#define _PID_PID_Automatic_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by class PID_PID_Automatic
 ******************************************************************************/
extern float32 PID_PID_Automatic_D_OUT ( const struct PID_PID_Automatic * self);
extern float32 PID_PID_Automatic_I_OUT ( const struct PID_PID_Automatic * self);
extern float32 PID_PID_Automatic_P_OUT ( const struct PID_PID_Automatic * self);
extern void PID_PID_Automatic_Regulator (
               const struct PID_PID_Automatic * self,
   /* IN    */ const float32                    PressureSet,
   /* IN    */ const float32                    InpPressure,
   /* IN    */ const float32                    qP,
   /* IN    */ const float32                    qI,
   /* IN    */ const float32                    qD,
   /* IN    */ const float32                    dT_
   );



#endif /* _ASD_PID_PID_AUTOMATIC_H_ */
