/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.5.0
 * CODE GENERATOR:..............V7.5.0
 * COMPONENT:...................SystemLib.Delay.DelayValue
 * REPRESENTATION:..............Impl
 * DESCRIPTION:
 *    DelayValue delays its input value by one evaluation step.
 ******************************************************************************/
#ifndef _ASD_SYSTEMLIB_DELAY_DELAYVALUE_IMPL_H_
#define _ASD_SYSTEMLIB_DELAY_DELAYVALUE_IMPL_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'SystemLib_Delay_DelayValue_Impl'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct SystemLib_Delay_DelayValue_Impl_RAM_SUBSTRUCT {
   float64 memory1;
   float64 memory2;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'SystemLib_Delay_DelayValue_Impl'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR CLASS 'SystemLib_Delay_DelayValue_Impl'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct SystemLib_Delay_DelayValue_Impl {
   struct SystemLib_Delay_DelayValue_Impl_RAM_SUBSTRUCT * SystemLib_Delay_DelayValue_Impl_RAM;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR CLASS 'SystemLib_Delay_DelayValue_Impl'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ............SystemLib_Delay_DelayValue_Impl */
#define _SystemLib_Delay_DelayValue_Impl_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by class SystemLib_Delay_DelayValue_Impl
 ******************************************************************************/
extern void SystemLib_Delay_DelayValue_Impl_compute (
               const struct SystemLib_Delay_DelayValue_Impl * self,
   /* IN    */ const float64                                  valCompute
   );
extern float64 SystemLib_Delay_DelayValue_Impl_value ( const struct SystemLib_Delay_DelayValue_Impl * self);



#endif /* _ASD_SYSTEMLIB_DELAY_DELAYVALUE_IMPL_H_ */
