/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.5.0
 * CODE GENERATOR:..............V7.5.0
 * COMPONENT:...................SystemLib.Delay.DelayValue
 * REPRESENTATION:..............Impl
 * DESCRIPTION:
 *    DelayValue delays its input value by one evaluation step.
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "SystemLib_Delay_DelayValue_Impl.h"
/******************************************************************************
 * BEGIN: source code of a multiple instance class
 ******************************************************************************/



#define memory1_VAL (self->SystemLib_Delay_DelayValue_Impl_RAM->memory1)
#define memory2_VAL (self->SystemLib_Delay_DelayValue_Impl_RAM->memory2)


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'SystemLib_Delay_DelayValue_Impl_compute'
 * ----------------------------------------------------------------------------
 * model name:...................................'compute'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void SystemLib_Delay_DelayValue_Impl_compute (
               const struct SystemLib_Delay_DelayValue_Impl * self,
   /* IN    */ const float64                                  valCompute
   )
{
   memory2_VAL = memory1_VAL;
   memory1_VAL = valCompute;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'SystemLib_Delay_DelayValue_Impl_compute'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'SystemLib_Delay_DelayValue_Impl_value'
 * ----------------------------------------------------------------------------
 * model name:...................................'value'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float64 SystemLib_Delay_DelayValue_Impl_value ( const struct SystemLib_Delay_DelayValue_Impl * self)
{
   return memory2_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'SystemLib_Delay_DelayValue_Impl_value'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



